spring.datasource.url=jdbc:postgresql://localhost:5432/petshop_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# =======================================================
# CONFIGURACION DE HIBERNATE / JPA
# =======================================================
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Para resetar tablas            //// cambiamos entre create cuando queramos que se creen las tablas o upadte para actualizar (va de la mano con always o never)
spring.jpa.hibernate.ddl-auto=create     

# Muestra y formatea las consultas SQL en la consola para depuracion
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =======================================================
# INICIALIZACION DE DATOS (DATA.SQL)
# =======================================================
# 1. Obliga a Spring Boot a esperar que Hibernate valide o cree las tablaDs primero
spring.jpa.defer-datasource-initialization=true

# 2. Le indica el nombre exacto de tu archivo con los inserts iniciales
spring.sql.init.data-locations=classpath:Insert_Base.sql

# 3. Se mantiene en 'never' porque los datos ya existen en tu PostgreSQL//// vamos cambiando entre always cuando queramos q los ingrese o never cuando ya existen
spring.sql.init.mode=always

spring.sql.init.encoding=UTF-8