# ========================================================
# CONEXION A POSTGRESQL
# ========================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/petshop_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# ========================================================
# CONFIGURACION DE HIBERNATE / JPA
# ========================================================
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 'validate' es el mejor modo porque ya creamos las tablas a mano.
# Spring Boot solo verificara que tus clases Java coincidan.
spring.jpa.hibernate.ddl-auto=validate

# Muestra y formatea las consultas SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true