# CONFIGURACI�N DE CONEXI�N A MYSQL (REQ6)
spring.datasource.url=jdbc:mysql://localhost:3306/petshop_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1234

# DRIVER CORRECTO PARA MYSQL (Esto soluciona el error actual)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# CONFIGURACI�N DE HIBERNATE PARA CREACI�N AUTOM�TICA (REQ7)./mvnw clean install -U
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# EST�NDAR SPRING BOOT PARA CARGA DE DATOS DML (REQ5)
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# CONFIGURACIÓN DEL ARCHIVO DE LOGS (REQ10)
logging.file.name=logs/backend.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n